/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasourcesIndexRouteImport } from './routes/datasources/index'
import { Route as DatasourcesNewRouteImport } from './routes/datasources/new'
import { Route as DatasourcesIdRouteImport } from './routes/datasources/$id'
import { Route as DatasourcesIdIndexRouteImport } from './routes/datasources/$id/index'
import { Route as DatasourcesIdTestRouteImport } from './routes/datasources/$id/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesIndexRoute = DatasourcesIndexRouteImport.update({
  id: '/datasources/',
  path: '/datasources/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesNewRoute = DatasourcesNewRouteImport.update({
  id: '/datasources/new',
  path: '/datasources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesIdRoute = DatasourcesIdRouteImport.update({
  id: '/datasources/$id',
  path: '/datasources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesIdIndexRoute = DatasourcesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DatasourcesIdRoute,
} as any)
const DatasourcesIdTestRoute = DatasourcesIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => DatasourcesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasources/$id': typeof DatasourcesIdRouteWithChildren
  '/datasources/new': typeof DatasourcesNewRoute
  '/datasources/': typeof DatasourcesIndexRoute
  '/datasources/$id/test': typeof DatasourcesIdTestRoute
  '/datasources/$id/': typeof DatasourcesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasources/new': typeof DatasourcesNewRoute
  '/datasources': typeof DatasourcesIndexRoute
  '/datasources/$id/test': typeof DatasourcesIdTestRoute
  '/datasources/$id': typeof DatasourcesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasources/$id': typeof DatasourcesIdRouteWithChildren
  '/datasources/new': typeof DatasourcesNewRoute
  '/datasources/': typeof DatasourcesIndexRoute
  '/datasources/$id/test': typeof DatasourcesIdTestRoute
  '/datasources/$id/': typeof DatasourcesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasources/$id'
    | '/datasources/new'
    | '/datasources/'
    | '/datasources/$id/test'
    | '/datasources/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasources/new'
    | '/datasources'
    | '/datasources/$id/test'
    | '/datasources/$id'
  id:
    | '__root__'
    | '/'
    | '/datasources/$id'
    | '/datasources/new'
    | '/datasources/'
    | '/datasources/$id/test'
    | '/datasources/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasourcesIdRoute: typeof DatasourcesIdRouteWithChildren
  DatasourcesNewRoute: typeof DatasourcesNewRoute
  DatasourcesIndexRoute: typeof DatasourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/': {
      id: '/datasources/'
      path: '/datasources'
      fullPath: '/datasources/'
      preLoaderRoute: typeof DatasourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/new': {
      id: '/datasources/new'
      path: '/datasources/new'
      fullPath: '/datasources/new'
      preLoaderRoute: typeof DatasourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/$id': {
      id: '/datasources/$id'
      path: '/datasources/$id'
      fullPath: '/datasources/$id'
      preLoaderRoute: typeof DatasourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/$id/': {
      id: '/datasources/$id/'
      path: '/'
      fullPath: '/datasources/$id/'
      preLoaderRoute: typeof DatasourcesIdIndexRouteImport
      parentRoute: typeof DatasourcesIdRoute
    }
    '/datasources/$id/test': {
      id: '/datasources/$id/test'
      path: '/test'
      fullPath: '/datasources/$id/test'
      preLoaderRoute: typeof DatasourcesIdTestRouteImport
      parentRoute: typeof DatasourcesIdRoute
    }
  }
}

interface DatasourcesIdRouteChildren {
  DatasourcesIdTestRoute: typeof DatasourcesIdTestRoute
  DatasourcesIdIndexRoute: typeof DatasourcesIdIndexRoute
}

const DatasourcesIdRouteChildren: DatasourcesIdRouteChildren = {
  DatasourcesIdTestRoute: DatasourcesIdTestRoute,
  DatasourcesIdIndexRoute: DatasourcesIdIndexRoute,
}

const DatasourcesIdRouteWithChildren = DatasourcesIdRoute._addFileChildren(
  DatasourcesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasourcesIdRoute: DatasourcesIdRouteWithChildren,
  DatasourcesNewRoute: DatasourcesNewRoute,
  DatasourcesIndexRoute: DatasourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
