/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportIndexRouteImport } from './routes/import/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as DatasourcesIndexRouteImport } from './routes/datasources/index'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards/index'
import { Route as DatasourcesNewRouteImport } from './routes/datasources/new'
import { Route as DatasourcesIdRouteImport } from './routes/datasources/$id'
import { Route as DashboardsNewRouteImport } from './routes/dashboards/new'
import { Route as DatasourcesIdIndexRouteImport } from './routes/datasources/$id/index'
import { Route as DashboardsIdIndexRouteImport } from './routes/dashboards/$id/index'
import { Route as DatasourcesIdTestRouteImport } from './routes/datasources/$id/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportIndexRoute = ImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesIndexRoute = DatasourcesIndexRouteImport.update({
  id: '/datasources/',
  path: '/datasources/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesNewRoute = DatasourcesNewRouteImport.update({
  id: '/datasources/new',
  path: '/datasources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesIdRoute = DatasourcesIdRouteImport.update({
  id: '/datasources/$id',
  path: '/datasources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsNewRoute = DashboardsNewRouteImport.update({
  id: '/dashboards/new',
  path: '/dashboards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesIdIndexRoute = DatasourcesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DatasourcesIdRoute,
} as any)
const DashboardsIdIndexRoute = DashboardsIdIndexRouteImport.update({
  id: '/dashboards/$id/',
  path: '/dashboards/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesIdTestRoute = DatasourcesIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => DatasourcesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboards/new': typeof DashboardsNewRoute
  '/datasources/$id': typeof DatasourcesIdRouteWithChildren
  '/datasources/new': typeof DatasourcesNewRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/datasources/': typeof DatasourcesIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/import/': typeof ImportIndexRoute
  '/datasources/$id/test': typeof DatasourcesIdTestRoute
  '/dashboards/$id/': typeof DashboardsIdIndexRoute
  '/datasources/$id/': typeof DatasourcesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboards/new': typeof DashboardsNewRoute
  '/datasources/new': typeof DatasourcesNewRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/datasources': typeof DatasourcesIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/import': typeof ImportIndexRoute
  '/datasources/$id/test': typeof DatasourcesIdTestRoute
  '/dashboards/$id': typeof DashboardsIdIndexRoute
  '/datasources/$id': typeof DatasourcesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboards/new': typeof DashboardsNewRoute
  '/datasources/$id': typeof DatasourcesIdRouteWithChildren
  '/datasources/new': typeof DatasourcesNewRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/datasources/': typeof DatasourcesIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/import/': typeof ImportIndexRoute
  '/datasources/$id/test': typeof DatasourcesIdTestRoute
  '/dashboards/$id/': typeof DashboardsIdIndexRoute
  '/datasources/$id/': typeof DatasourcesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboards/new'
    | '/datasources/$id'
    | '/datasources/new'
    | '/dashboards/'
    | '/datasources/'
    | '/explore/'
    | '/import/'
    | '/datasources/$id/test'
    | '/dashboards/$id/'
    | '/datasources/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboards/new'
    | '/datasources/new'
    | '/dashboards'
    | '/datasources'
    | '/explore'
    | '/import'
    | '/datasources/$id/test'
    | '/dashboards/$id'
    | '/datasources/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboards/new'
    | '/datasources/$id'
    | '/datasources/new'
    | '/dashboards/'
    | '/datasources/'
    | '/explore/'
    | '/import/'
    | '/datasources/$id/test'
    | '/dashboards/$id/'
    | '/datasources/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardsNewRoute: typeof DashboardsNewRoute
  DatasourcesIdRoute: typeof DatasourcesIdRouteWithChildren
  DatasourcesNewRoute: typeof DatasourcesNewRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
  DatasourcesIndexRoute: typeof DatasourcesIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ImportIndexRoute: typeof ImportIndexRoute
  DashboardsIdIndexRoute: typeof DashboardsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/': {
      id: '/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof ImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/': {
      id: '/datasources/'
      path: '/datasources'
      fullPath: '/datasources/'
      preLoaderRoute: typeof DatasourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/new': {
      id: '/datasources/new'
      path: '/datasources/new'
      fullPath: '/datasources/new'
      preLoaderRoute: typeof DatasourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/$id': {
      id: '/datasources/$id'
      path: '/datasources/$id'
      fullPath: '/datasources/$id'
      preLoaderRoute: typeof DatasourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/new': {
      id: '/dashboards/new'
      path: '/dashboards/new'
      fullPath: '/dashboards/new'
      preLoaderRoute: typeof DashboardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/$id/': {
      id: '/datasources/$id/'
      path: '/'
      fullPath: '/datasources/$id/'
      preLoaderRoute: typeof DatasourcesIdIndexRouteImport
      parentRoute: typeof DatasourcesIdRoute
    }
    '/dashboards/$id/': {
      id: '/dashboards/$id/'
      path: '/dashboards/$id'
      fullPath: '/dashboards/$id/'
      preLoaderRoute: typeof DashboardsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources/$id/test': {
      id: '/datasources/$id/test'
      path: '/test'
      fullPath: '/datasources/$id/test'
      preLoaderRoute: typeof DatasourcesIdTestRouteImport
      parentRoute: typeof DatasourcesIdRoute
    }
  }
}

interface DatasourcesIdRouteChildren {
  DatasourcesIdTestRoute: typeof DatasourcesIdTestRoute
  DatasourcesIdIndexRoute: typeof DatasourcesIdIndexRoute
}

const DatasourcesIdRouteChildren: DatasourcesIdRouteChildren = {
  DatasourcesIdTestRoute: DatasourcesIdTestRoute,
  DatasourcesIdIndexRoute: DatasourcesIdIndexRoute,
}

const DatasourcesIdRouteWithChildren = DatasourcesIdRoute._addFileChildren(
  DatasourcesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardsNewRoute: DashboardsNewRoute,
  DatasourcesIdRoute: DatasourcesIdRouteWithChildren,
  DatasourcesNewRoute: DatasourcesNewRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
  DatasourcesIndexRoute: DatasourcesIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ImportIndexRoute: ImportIndexRoute,
  DashboardsIdIndexRoute: DashboardsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
